apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-websecure
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-headers
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
    accessControlAllowOriginList:
      - "https://www.digitimagepredictor.com"
    accessControlAllowHeaders:
      - "Content-Type"
      - "Authorization"
    accessControlMaxAge: 100
    addVaryHeader: true
    accessControlAllowCredentials: false
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.digitimagepredictor.com`) && PathPrefix(`/predict`)
      kind: Rule
      services:
        - name: digit-image-predictor-app-service
          port: 80
      middlewares:
        - name: cors-headers
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingressroute-http-redirect
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.digitimagepredictor.com`)
      kind: Rule
      services:
        - name: digit-image-predictor-app-service
          port: 80
      middlewares:
        - name: redirect-to-websecure