apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-headers
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - "POST"
      - "OPTIONS"
    accessControlAllowOriginList:
      - "*" # Frontend URL, temporarily * for testing
    accessControlMaxAge: 100
    addVaryHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`172.168.84.5`) && PathPrefix(`/predict`) && Method(`POST`)
      kind: Rule
      services:
        - name: digit-image-predictor-app-service
          port: 80
      middlewares:
        - name: cors-headers
          namespace: default