apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: digit-image-predictor-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Alkamist/mnist-digit-predictor
    targetRevision: HEAD
    path: helm-chart
    helm:
      values: |
        server:
          replicaCount: 1
          runLocally: true
        worker:
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true