apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  annotations:
    # Use sync-wave 1 for dependencies. This ensures it's deployed first.
    argocd.argoproj.io/sync-wave: "1" 
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.x.x
    chart: rabbitmq
    helm:
      values: |
        replicaCount: 1
        image:
          registry: docker.io
          repository: bitnamilegacy/rabbitmq
          tag: 4.1.3-debian-12-r1
  destination:
    server: https://kubernetes.default.svc
    namespace: dependencies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true