apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-instance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Alkamist/mnist-digit-predictor-argocd
    targetRevision: HEAD
    path: apps/rabbitmq-instance
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true